services:
  hairdobooking_frontend:
    build:
      context: .
      target: prod
    container_name: hairdobooking_frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://admin.hairdobooking.com
    networks:
      - prod-network
    restart: always

networks:
  prod-network:
    driver: bridge
