services:
  hairdobooking_frontend_qa:
    build:
      context: .
      target: prod
    container_name: hairdobooking_frontend_qa
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://adminqa.hairdobooking.com
    networks:
      - qa-network
    restart: always

networks:
  qa-network:
    driver: bridge
