services:
  hairdobooking_frontend:
    build:
      context: .
      target: dev
    container_name: hairdobooking_frontend_local
    ports:
      - "3804:3000"
    volumes:
      - ./:/usr/src/app
    networks:
      - app-network
      - shared-network
    environment:
      - HOST=0.0.0.0
      - PORT=3000

networks:
  app-network:
    driver: bridge
  shared-network:
    external: true
