services:
  hairdobooking_frontend_qa:
    container_name: hairdobooking_frontend_qa

    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NO_CACHE=1

    image: hairdobooking_frontend_qa:latest

    ports:
      - "3001:3000"

    environment:
      NODE_ENV: production

    networks:
      - qa-network

    restart: always

networks:
  qa-network:
    driver: bridge
